### ISSUE TITLE
Categorise games

### ISSUE THREAD

**Issue by doppioslash** [rust-gamedev/arewegameyet#100]
There are now enough games to warrant some categorisation.
My idea would be to divide them in 3/4:

- Commercial
- Game Jam
- Open Source
- Freeware

I think we have a few games that ended up on steam/mobile which are a good fit for the Commercial category. There is also the Chucklefish game, Spellbound, which I think we can already list.

**Comment by ozkriff** [comment]
How about an additional finished/abandoned/work-in-progress categorization?

**Comment by doppioslash** [comment]
Yeah. Maybe that could be a label, rather than a category?
