### ISSUE TITLE
Add a "Community" page

### ISSUE THREAD

**Issue by erlend-sh** [rust-gamedev/arewegameyet#102]
There are a couple of standard community spaces for talking about Rust gamedev that I think are worthwhile to point out.

**Forum:**

https://reddit.com/r/rust_gamedev/

**Chat:**

https://discordapp.com/invite/aVESxV8
Join the #gamedev channel.

https://gitter.im/rust-gamedev (less active)

[#rust-gamedev](#rust-gamedev) on irc.mozilla.org

**Twitter:**

https://twitter.com/rust_gamedev
https://twitter.com/hashtag/screenshotsaturday+rustlang

(not a common thing yet but it would be good to encourage rust gamedevs to participate in this. [Trying to raise some awareness of it as we speak.](https://old.reddit.com/r/rust_gamedev/comments/9bjost/participate_in_screenshotsaturday_rustlang_on/))

**Learning:**

http://arewegameyet.com/#resources

(anchor link currently doesn't work. Could also be updated with a lot of new resources, I'll do some PRs)

**Comment by ozkriff** [comment]
Most of these seem to be already done, right?
- subreddit is mentioned
- irc chat is mentioned
- discord char on the community server is mentioned
- twitter is mentioned

------

Gitter chat isn't mentioned, but at this point, it looks to be completely dead (@kvark maybe we should archive it?).

https://twitter.com/hashtag/screenshotsaturday+rustlang isn't mentioned, but I'm not sure if just mentioning it on AWGY is enough - people still don't participate in SSS. I'm afraid that this link on AWGY may look offputting to newcomers.
