### ISSUE TITLE
Use CI to build for GH Pages or Netlify

### ISSUE THREAD

**Issue by piedoom** [rust-gamedev/arewegameyet#129]
As far as I know GH pages only supports Jekyll.  Zola's documentation as well as all of my own sites built with the tool use [Netlify](https://www.netlify.com/) (which I'm sure you already know of) which has built in support for various static gens including Zola.  It would require moving stuff around, and is difficult to co-organize with any other users though.

Alternatively, perhaps it would make sense to set up Travis or some other CI service to build & push to the existing GH pages [as I documented here](https://www.getzola.org/documentation/deployment/github-pages/)?  This would be pretty easy and require no extra setup outside of the CI.  

If either of these sounds good, let me know or tell me if you think another approach is a better idea.

**Comment by doppioslash** [comment]
It's not on github pages, it's on AWS S3.

**Comment by piedoom** [comment]
Ok!  Sounds good.  Do you need anything to get that running or should I close this?

**Comment by ozkriff** [comment]
Done in https://github.com/rust-gamedev/arewegameyet/pull/219
