### ISSUE TITLE
Sort entries

### ISSUE THREAD

**Issue by piedoom** [rust-gamedev/arewegameyet#157]
As per the suggestion [here](https://github.com/doppioslash/arewegameyet/issues/12#issuecomment-454373575) it would be a good idea to make sure the positioning of data items is consistent.  I recommend alphabetical, as popularity cannot be measured well for many crates not on GH.

**Comment by mbillingr** [comment]
I had thought about number of downloads, but this only works for crates.io and would favor old and low-level crates. Alphabetical feels like the better criterion ATM.

**Comment by ozkriff** [comment]
If we decide to use alphabetical order, we definitely need to check that on CI. Also, do we want to also sort games and resources (for consistency)?

**Comment by 17cupsofcoffee** [comment]
Could we sort the categories in [the template](https://github.com/rust-gamedev/arewegameyet/blob/master/templates/categories/page.html#L190) using Tera's [`sort` filter](https://tera.netlify.com/docs/#sort)? Would save us having to do it manually, but I'm not sure whether it'd adversely affect build times.

**Comment by 17cupsofcoffee** [comment]
The Zola builds for my commits on #242 seem to run just as fast as the ones on master, which is both surprising and promising!

As mentioned on the description though, manual sorting could still be beneficial (either instead of or in addition to my PR) to make the files easier to navigate and to reduce any potential overhead as the site grows.

**Comment by ozkriff** [comment]
I'll send another PR that will sort games and resources too and add CI check in a few hours..

**Comment by ozkriff** [comment]
So, do we want to sort games and resources alphabetically too?

**Comment by ozkriff** [comment]
Btw, here's a basic python script that can auto-sort the data files for CI tests:

```python
import toml
import fileinput

for path in fileinput.input():
    path = path.strip()
    print(f"'{path}'")
    data = toml.load(path)
    for (name, entries) in data.items():
        entries.sort(key=lambda entry: entry['name'])
    with open(path, 'w') as f:
        toml.dump(data, f)
```
