### ISSUE TITLE
Transfer ownership to Rust Gamedev Working Group

### ISSUE THREAD

**Issue by termhn** [rust-gamedev/arewegameyet#210]
Hi!
This is an awesome resource and is frequently linked; unfortunately, it doesn't get updated to frequently (entirely understandable, I know how it goes!)

Would you be open to transferring ownership of maintainership/this repo to the [rust gamedev-wg](https://github.com/rust-gamedev/wg)? I think this would be a great solution to having more active maintainership being shared among more people so that we can have a more active central hub for Rust gamedev resources.

I've created a [sister issue](https://github.com/rust-gamedev/wg/issues/64) on the rust-gamedev/wg issue tracker as well.

**Comment by ozkriff** [comment]
Related: #110 (_"Move to rustgd"_)

**Comment by termhn** [comment]
Ah, thought I searched and didn't see anything, but evidently didn't search hard enough :sweat_smile:

**Comment by doppioslash** [comment]
If the wg is interested, yeah.

**Comment by ozkriff** [comment]
Yeah, the WG is definitely interested!

Have you received an invite from the WG?

I volunteer to do the migration to Github Pages - https://ozkriff.games/arewegameyet from [my fork](https://github.com/ozkriff/arewegameyet) seems to work fine.

**Comment by doppioslash** [comment]
Yeah, accepted the invite. What's next?

**Comment by ozkriff** [comment]
Now you should be able [to transfer this repo](https://help.github.com/en/github/administering-a-repository/transferring-a-repository) to the @rust-gamedev org.

**Comment by doppioslash** [comment]
done.

**Comment by the-false-gamer** [comment]
ummmm, this issue should be closed.

**Comment by ozkriff** [comment]
JFYI: `.com` and `.org` domains have been finally transferred, they now point to Github Pages version of the site.
