### ISSUE TITLE
Hyperlink to amethyst game engine 404

### ISSUE THREAD

**Issue by ruabmbua** [rust-gamedev/arewegameyet#212]
Hyperlink to amethyst game engine wrong. It should point to https://amethyst.rs

**Comment by 17cupsofcoffee** [comment]
Which link do you mean? The one on http://arewegameyet.com/categories/engines works fine for me.

**Comment by ruabmbua** [comment]
J ust realized I was not using the main link. I attached a image. The dead link is on the main page.

![Screenshot_2019-10-29 Are we game yet - Rust](https://user-images.githubusercontent.com/2522373/67803590-a9589b80-fa8d-11e9-9ed9-29ed5252ea84.png)
