### ISSUE TITLE
"Legion" not showing up on published site

### ISSUE THREAD

**Issue by canadaduane** [rust-gamedev/arewegameyet#229]
I'm not sure why this is happening, but it appears that `Legion` ECS is not showing up on the published site. I can see it in the [ECS TOML file](https://github.com/rust-gamedev/arewegameyet/blob/master/content/categories/ecs/data.toml) (there are 14 ECS crates enumerated), so it has been added; however, the [ECS Category](http://arewegameyet.com/categories/ecs/) does not currently list it (there are 13 ECS crates listed).

Could this be an issue with gh-pages?

**Comment by 17cupsofcoffee** [comment]
Interestingly, the `gh-pages` branch actually has the HTML for `legion`: https://github.com/rust-gamedev/arewegameyet/blob/gh-pages/categories/ecs/index.html#L1429

So this either seems like a caching issue or an issue with the GitHub Pages config?

**Comment by doppioslash** [comment]
Fixed now.
This happens because the wg still needs to setup the domain transfer.
I still have the dns and they're pointing to the legacy website, which is not automatically updated.
