### ISSUE TITLE
Split games and resources into categories

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/arewegameyet#252]
Crates are already split into categories.

It seems to me that we should split games and resources into categories too (like action/puzzle/strategy/simulation/etc and articles/videos/tutorials/etc) because otherwise, the main page will explode if we add all the rust games and interesting articles/tutorials to it without any structure.

Optionally, we could show a few randomly selected game/resource cards on the main page, but that another issue.

Related to #157 (_"Sort entries"_)

**Comment by ozkriff** [comment]
Ouch, a similar issue was already opened - #100 (_"Categorise games"_). Though it talks about another kind of categorization.

**Comment by 17cupsofcoffee** [comment]
Another upside to this would be not having all of the images on one page - https://arewegameyet.rs is currently a 24MB download with a clean cache 😱

Admittedly a lot of that is people submitting way too big images, but even if they were reasonably sized, it'd still add up over time.

**Comment by 17cupsofcoffee** [comment]
I'm going to have a go at implementing this at some point, so I've assigned the issue to myself.

**Comment by 17cupsofcoffee** [comment]
I had a look at this over the weekend - the tricky thing is that crates, games and resources have evolved to have *sliiiightly* different UI/schemas, so it's not totally straightforward to adapt the existing category templates. Not sure whether the best approach is to figure out a better unified TOML schema/look for the categories, or to just accept the fact that some code is going to be duplicated. I'll have a play around with both approaches.
