### ISSUE TITLE
Site fails to build on Zola 0.10

### ISSUE THREAD

**Issue by 17cupsofcoffee** [rust-gamedev/arewegameyet#257]
The site currently fails to build on the newest version of Zola. This seems to be due to https://github.com/getzola/zola/issues/950 (`load_data` isn't sending a `User-Agent` header any more, and GitHub/Crates.io won't let you call their APIs without it).

Not a huge issue (0.9 still works fine), but thought I'd raise a tracking issue so that people don't get confused if they run into the same problem!

**Comment by 17cupsofcoffee** [comment]
A fix (https://github.com/getzola/zola/pull/952) has been merged to Zola, so hopefully 0.10.1 isn't too far off being released 😄

**Comment by ozkriff** [comment]
Waiting for https://github.com/getzola/zola/pull/951

**Comment by ozkriff** [comment]
Zola v0.10.1 is out!

https://github.com/getzola/zola/releases/tag/v0.10.1

**Comment by Keats** [comment]
Damn faster than I could write!
Sorry about the delay, I was moving and completely forgot about it.

**Comment by 17cupsofcoffee** [comment]
Can confirm the site builds with the latest version :)
