### ISSUE TITLE
Fix https redirect from arewegameyet.rs

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/arewegameyet#260]
The http redirect from http://arewegameyet.rs works fine, but something's wrong with https certificate  and I can't figure out how to fix it on ninet.rs's admin panel yet.

Related to #7 (_"Use https"_)

**Comment by ozkriff** [comment]
Should be fixed by #261 (_"Make .rs domain primary?"_)

**Comment by Wodann** [comment]
I can confirm it's fixed. Nice work 👌🏻
