### ISSUE TITLE
Make .rs domain primary?

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/arewegameyet#261]
https://arewegameyet.com URL doesn't express any relation to Rust on its own.

Maybe we should make arewegameyet.rs the primary URL and redirect com/org to it? 

I guess that [Areweyet](https://wiki.mozilla.org/Areweyet)-thing was initially meant only for .com domains, but https://areweasyncyet.rs already breaks that pattern.

What do you think?

**Comment by AlexEne** [comment]
Sounds good to me.

**Comment by 17cupsofcoffee** [comment]
I have no strong opinions either way - if people feel like it would make the Rust association more obvious, then go for it :)

**Comment by Wodann** [comment]
I like the idea 👍

**Comment by repi** [comment]
Like it!

**Comment by ozkriff** [comment]
:warning:  :construction:

**Comment by Wodann** [comment]
It's working for me. Nice work 👌🏻

**Comment by ozkriff** [comment]
Well, everything worked fine, except for https redirects from com and org domains that just were not responding:
<details>
  <summary>It turned out that https redirection in our case isn't as easy as I expected.</summary>

  ![image](https://user-images.githubusercontent.com/662976/85042339-c6b0b600-b193-11ea-9836-0fdebd4ad264.png)

</details>

And that's kinda bad because there're many arewegameyet.com links on the internet, including Google search results that may stay in the cache for months.

But thanks to @17cupsofcoffee a  well-functioning and relatively simple solution employing [netlify's splat redirects](https://docs.netlify.com/routing/redirects/redirect-options/#splats) was found:

1) Created a https://arewegameyet-redirect.netlify.app dummy site following @17cupsofcoffee's instructions: 

  > ...
  >
  > * create a new folder with a blank index.html and a file called _redirects
  > * in the _redirects, add this (the ! basically forces it to ignore matching files in the folder and always redirect):
  > ```text
  > /* https://arewegameyet.rs/:splat 301!
  > /  https://arewegameyet.rs 301!
  > ```
  > * deploy that to netlify, either as a repo or just via drag and drop
  >
  > ...
  >
  > the only quirky thing I ran into was the fact it wouldn't deploy properly without an index.html, but if you have an index.html that takes precedence over the redirect for / but adding the 301! to the config disables that behavior (https://docs.netlify.com/routing/redirects/rewrites-proxies/#shadowing)
2) Added arewegameyet.com as a primary custom domain and replace Namecheap's DNS with Netlify's DNS
3) Added arewegameyet.org as a secondary custom domain and did the same with DNS
4) Waited for the DNS changes to propagate and asked Netlify to create a Let's Encrypt certificate for all this mess)

And voila! all the

* http://arewegameyet.com
* http://arewegameyet.org
* http://arewegameyet.rs
* https://arewegameyet.com
* https://arewegameyet.org
* https://arewegameyet.rs

work now and 301-redirect to https://arewegameyet.rs.

And in addition to that, all the paths are redirected correctly too: `http://arewegameyet.org/games/strategy` -> `https://arewegameyet.rs/games/strategy`, yay! :)
