### ISSUE TITLE
Floating navbar is too wide on mobile

### ISSUE THREAD

**Issue by 17cupsofcoffee** [rust-gamedev/arewegameyet#268]
I'm not sure if this has always been the case or whether it was a bug in one of my earlier PRs, but the floating navbar does not fit on the screen on mobile devices - you can't click the two big buttons on the right.

We should probably make it so the links get replaced with a hamburger menu on small screens, like the ones on the static navigation at the top of the page do.

(As an aside: it seems weird to me that there's a big button for 'Resources', while the other sections only have links 🤔)

**Comment by ozkriff** [comment]
Related to https://github.com/rust-gamedev/arewegameyet/issues/52

Do we really need this glued navbar at all?

> it seems weird to me that there's a big button for 'Resources', while the other sections only have links

yeah, it seems to be just a historical artifact

**Comment by 17cupsofcoffee** [comment]
Also, I totally broke the link to `resources` in #255, doh. Will fix!
