### ISSUE TITLE
Mention new Discord server

### ISSUE THREAD

**Issue by ozkriff** [rust-gamedev/arewegameyet#297]
https://rust-gamedev.github.io/posts/newsletter-007/#new-rust-gamedev-discord-server

**Comment by 17cupsofcoffee** [comment]
👍 

Somewhat related: does the gamedev IRC actually still exist now that Mozilla's IRC server has shut down? If not, would be good to remove it when we add this.

**Comment by ozkriff** [comment]
Makes sense - that IRC channel is totally dead now.
