### ISSUE TITLE
Add game: Ascension 2

### ISSUE THREAD

**Issue by outkine** [rust-gamedev/arewegameyet#308]
Please add game to category: Platformer. [Source code](https://github.com/outkine/ascension-rust), [itch.io page](https://outkine.itch.io/ascension-2). Made with ggez and nphysics2d.

**Comment by 17cupsofcoffee** [comment]
@ozkriff has already got a PR (https://github.com/rust-gamedev/arewegameyet/pull/307) raised to add it 😄

**Comment by outkine** [comment]
This is why I love this community 😀. Closing...
