### ISSUE TITLE
Add crate: polyhedron-ops

### ISSUE THREAD

**Issue by virtualritz** [rust-gamedev/arewegameyet#379]
Please add crate to category: Mesh Tools

Note that this crate – can, among many other things –, be used to create spheres made (almost entirely) from hexagons. To do this you start with a `dodecahedron` base shape and apply `kis` and `dual` any number of times.

This may be useful for some people as the crate with the name `hexasphere` actually creates a sphere that is made of triangles, not hexagons.

**Comment by ozkriff** [comment]
fyi: also shared about the crate from our Twitter https://twitter.com/rust_gamedev/status/1337496964389359619

**Comment by virtualritz** [comment]
Thank you! :)
Heaps appreciated.
