### ISSUE TITLE
License of the code / repository

### ISSUE THREAD

**Issue by niclashoyer** [rust-gamedev/arewegameyet#381]
I'm evaluating options for a new `are we X yet` site. While most of the generators use `zola`, every one seems to have its own structure.

[`arewewebyet`](https://github.com/rust-lang/arewewebyet) has a CC license. Does this project have a license? Otherwise it would be hard to fork / reuse it.

**Comment by ozkriff** [comment]
I believe it's CC-BY: https://github.com/rust-gamedev/arewegameyet/blob/HEAD/templates/master.html#L90

**Comment by ozkriff** [comment]
Closing, but feel free to reopen if needed

**Comment by 17cupsofcoffee** [comment]
It might be worth adding a `LICENSE` file to the repo, just so it shows up in Github's UI as well as the site itself.
