### ISSUE TITLE
Suggestion: Performance Improvements

### ISSUE THREAD

**Issue by BezPowell** [rust-gamedev/arewegameyet#398]
I've been analysing the website performance and have a few suggestions for some things that might improve performance. The pagespeed insights score for the website on desktop and reasonably good, but mobile could use some work. Some of these are easy changes, some suggest removing things you might want to keep, and some are rather more in-depth:

## Easy changes:
- Self-host all of the CSS and JS that are currently being loaded via CDNs. This cuts down on DNS requests and TLS handshakes. In my testing it boosted performance by about 20 points for mobile. I can make a PR for this if there is interest (the changes are already in a branch of my fork). **EDIT:** This does have the downside that you don't get automatic bugfixes and have to manually update assets.
- Improve the cacheing for static assets. Netlify's default for this is a bit weird, but there's a plugin to hash everything and set expires headers automatically you can use: https://github.com/munter/netlify-plugin-hashfiles#readme This will improve performance for people browsing multiple pages on the site.
- **EDIT:** Self-hosting fonts would also improve performance for repeat visitors as Google have a rubbish cache policy on fonts served via fonts.google.com, requiring them to be re-downloaded on a regular basis.

## Harder changes
- Semantic UI's CSS and JS files are big. Uncompressed the main CSS file is almost a megabyte. I see on their site that they provide partial files and it should be possible to pull in only those components that you use via SASS. This could require going through the whole site and identifying only the CSS you use. It would have large performance wins however. I'm happy to dedicate some time to doing this at some point if there is interest.

## Controversial changes
- There are a few tracking scripts on the site which will slow down the page load quite a bit. My personal opinion on this is that you don't really need them as you're presumably not trying to profile visitors for the purposes of advertisement etc. Removing all tracking scripts would be quite a big gain to Time to Interactive as they are all loaded synchronously and thus will block page rendering - it will also be a win for user privacy.
This is me being evangelical about performance and web-privacy here though, so feel free to tell me to get lost.

I hope this all comes across okay. I think the website is a fantastic resource and these are just some suggestions on how to make it even better. You all are doing an amazing job maintaining it. I'm happy to have a go at making some of these changes if there is interest.

**Comment by 17cupsofcoffee** [comment]
The performance is a lot better than it used to be, but I would definitely like it to be better :) Here's my thoughts on the suggestions:

Easy changes:

* Self-hosting the CSS/JS seems fine IMO, if it measurably improves the load times. Semantic UI is unmaintained these days anyway, IIRC, so there's no updates for us to get :p
* The caching suggestion seems good, but we're not actually using Netlify for hosting currently - it's on GitHub Pages. I think there'd need to be a wider discussion/seperate issue about moving hosts, as while I prefer Netlify to GitHub's built-in offering, it would mean having to create new accounts/share access/etc.
* Self-hosting the fonts also seems like not a bad idea. I'd also not be opposed to just dropping the web fonts altogether and switching to system fonts, if it doesn't make the site look super ugly. My definition of 'super ugly' may not match other people's though 😛 

Harder changes:

* Anything that can reduce Semantic UI's size would be welcome, as long as it doesn't have too much of a maintainence burden.  It's the most bloated framework I've ever used and it drives me crazy 🙃 

(Not so) controversial changes:

* The tracking scripts (and the little Sumo pop-up in the top right) have been there since before the working group took over maintainence of the site, and I've never been able to get an answer as to what they're there for. I would be strongly in favour of removing them.

**Comment by 17cupsofcoffee** [comment]
I think the only thing to keep in mind when making any of these changes is that not a lot of the contributors and maintainers of this site are web devs. We ideally would not like to add any dependencies on JS tooling like NPM or Webpack or anything like that, as it would make it harder for people to contribute, and maintainance of it would probably fall solely on me 😅

Zola (the static site generator we use) has in-built SASS support though, so I don't think that'll be an issue, but seemed worth flagging up!

**Comment by BezPowell** [comment]
> I think the only thing to keep in mind when making any of these changes is that not a lot of the contributors and maintainers of this site are web devs. We ideally would not like to add any dependencies on JS tooling like NPM or Webpack or anything like that, as it would make it harder for people to contribute, and maintainance of it would probably fall solely on me sweat_smile
> 
> Zola (the static site generator we use) has in-built SASS support though, so I don't think that'll be an issue, but seemed worth flagging up!

Absolutely. I generally try and stay away from as much tooling as I can as in my experience it only adds to the confusion when more than one person is working on a site. I love Zola for its simplicity there.

I hadn't realised quite how monstrous semantic-ui was, cleaning that up would be quite a big task. With the other changes mentioned I've manged to get a mobile score of 91 on pagespeed insights. I am hosting my test changes on netlify though, so the server response times could be a bit different (github pages actually seems to be better at this). I don't know how github pages handles expires headers or if hashing assets would even be feasible there, so will do some research on that front. (Note: I'm not hashing on Netlify yet, so that won't have contributed to the improved score).

Thank you for being so understanding about the tracking scripts thing as well. I have very strong opinions on such things and have been told I can come across a bit too earnest :laughing:

Would you like me to open a PR with what I have done so far? Aside from the removal of the tracking scripts there should not be anything missing, just loading more efficiently. A major refactor of the CSS and framework would obviously further improve matters, but would be a much larger undertaking - if there is interest in it I might feel up to it at a later date.

**Comment by 17cupsofcoffee** [comment]
> Would you like me to open a PR with what I have done so far? 

Yes please! Not sure if I'll be able to review straight away, but I'll try to have a look in the next few days. Don't worry if the bigger refactors end up being too much work, even just these smaller changes will make a big impact :)

**Comment by 17cupsofcoffee** [comment]
Updated mobile Lighthouse audit:

![image](https://user-images.githubusercontent.com/784533/108633548-b3fe2780-746c-11eb-9398-cc8d1e4e1c27.png)

Success!
