### ISSUE TITLE
[issue] Error: Failed to render page '/home/user/git/arewegameyet/content/games/action.md'

### ISSUE THREAD

**Issue by ncorder** [rust-gamedev/arewegameyet#452]
**Issue**: can't `serve` site

___________________________

**Log**: 

```
[user@fedora arewegameyet]$ zola serve
Building site...
-> Creating 37 pages (0 orphan), 3 sections, and processing 0 images
Error: Failed to render page '/home/user/git/arewegameyet/content/games/action.md'
Reason: Failed to render 'categories/page.html'
Reason: Function call 'get_page' failed
Reason: Page `/games/action.md` not found.
[user@fedora arewegameyet]$ 
```

**Comment by ozkriff** [comment]
I guess the issue is that AWGY uses an old Zola (and that it's not mentioned in the README at all)

https://github.com/rust-gamedev/arewegameyet/blob/d3ff73b8dc0726b17d85a78e2aa81c2b7aff3284/.github/workflows/ci.yml#L14

**Comment by 17cupsofcoffee** [comment]
The newsletter site is also behind on Zola updates - if I get time after this month's newsletter, I'll try to update them both.
