### ISSUE TITLE
Anchors for permanent links to crates are off

### ISSUE THREAD

**Issue by bwasty** [rust-gamedev/arewegameyet#52]
Because of the fixed top navigation, the name of the crate is not visible when using the permanent links. Example: http://arewegameyet.com/categories/3dformatloader.html#gltf

**Comment by GloverDonovan** [comment]
This occurs for all permalinks, not just crates. This issue is very common and is easy to fix, although I question the usefulness of this fixed navigation in the first place.

**Comment by tpltnt** [comment]
Is this still an issue?

**Comment by tpltnt** [comment]
ping
