### ISSUE TITLE
"Creating a Snake Clone With Bevy" tutorial dead

### ISSUE THREAD

**Issue by mersenne-twister** [rust-gamedev/arewegameyet#557]
The tutorial "[Creating a Snake Clone With Bevy](https://mbuffett.com/posts/bevy-snake-tutorial/)" in the Tutorials section of Resources leads to a dead link. It could be removed, or it could be changed to point at the waybackmachine archive: "http://web.archive.org/web/20230405220535/https://mbuffett.com/posts/bevy-snake-tutorial/"; since the tutorial is still available there and it still may help someone, even if the original link is dead.

**Comment by yyogo** [comment]
Works for me.

**Comment by 17cupsofcoffee** [comment]
Yep, looks like it's back from the dead. Closing this for now, if it vanishes again we can decide on whether it should be archived 👍
