### ISSUE TITLE
Question: Is it necessary to publish crates on crates.io first?

### ISSUE THREAD

**Issue by JulianKnodt** [rust-gamedev/arewegameyet#584]
Please add crate to category: 3D Format Loaders
I've been working on a 3D model loading crate [here](https://github.com/JulianKnodt/pars3d), and was wondering if it was necessary to publish it to crates.io before listing it?

It's still under active development, but I'd like to have some people test it out.

**Comment by 17cupsofcoffee** [comment]
No, you don't need to publish to Crates.io - you can either provide the details manually, or set the `source` as GitHub to have the site pull the details from there automatically. See the [schema in the README](https://github.com/rust-gamedev/arewegameyet?tab=readme-ov-file#schema) for examples (or browse through the [`data.toml`](https://github.com/rust-gamedev/arewegameyet/blob/master/content/ecosystem/data.toml) to see how other people have added stuff).

**Comment by JulianKnodt** [comment]
cheers, thanks
