### ISSUE TITLE
Add Rust Roguelike

### ISSUE THREAD

**Issue by doppioslash** [rust-gamedev/arewegameyet#68]
https://github.com/richardanaya/rust-roguelike

**Comment by tpltnt** [comment]
I looked at it and there doesn't seem to be anything besides moving on the screen. This looks to me like a roguelike walking simulator (which has problems on the borders of the screen). Maybe close this issue?

**Comment by tpltnt** [comment]
ping

**Comment by WeirdConstructor** [comment]
There hasn't been any activity in the linked repository. I vote for closing this issue.

**Comment by tpltnt** [comment]
fine by me

**Comment by ozkriff** [comment]
Closing it if there're no objections.

**Comment by tpltnt** [comment]
please close
