### ISSUE TITLE
Use https

### ISSUE THREAD

**Issue by doppioslash** [rust-gamedev/arewegameyet#7]
This requires:
- getting a certificate form letsencrypt
- turning on cloudfront
- invalidation automation of the cloudfront cache
- which requires to move to cobalt-rs

So it waits on #12

**Comment by hellow554** [comment]
This issue is more than 2 years old and still no https! Please fix that!

**Comment by fakenine** [comment]
Hello to the maintainers :wave: 

Do you have an ETA for this issue ? 2 years and a half from now, most websites have migrated to HTTPS for privacy and security reasons...and most browsers are making it more and more visible that non-HTTPS websites are not secure.

**Comment by hellow554** [comment]
ping @doppioslash

**Comment by ozkriff** [comment]
Any updates on this? I've seen a few times that broken https://arewegameyet.rs and https://arewegameyet.com confused people.

**Comment by ozkriff** [comment]
Done: https://arewegameyet.com
